"""Prompt templates for AI Strategy Copilot."""

from .modification import MODIFICATION_PROMPT, MODIFICATION_SYSTEM_PROMPT, FIX_PROMPT
from .optimization import OPTIMIZATION_PROMPT, OPTIMIZATION_SYSTEM_PROMPT
from .explanation import EXPLANATION_PROMPT, EXPLANATION_SYSTEM_PROMPT

__all__ = [
    "MODIFICATION_PROMPT",
    "MODIFICATION_SYSTEM_PROMPT",
    "FIX_PROMPT",
    "OPTIMIZATION_PROMPT",
    "OPTIMIZATION_SYSTEM_PROMPT",
    "EXPLANATION_PROMPT",
    "EXPLANATION_SYSTEM_PROMPT",
]
